import './globals.css'

import { Montserrat } from 'next/font/google'

import CartProvider from './context/CartContext'

const montserrat = Montserrat({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

import {NextIntlClientProvider} from 'next-intl';
import {notFound} from 'next/navigation';
import CartMobileIcon from './components/CartMobileIcon'
import CartDesktop from './components/CartDesktop'
import CartMobile from './components/CartMobile'
 
export function generateStaticParams() {
  return [{locale: 'en'}, {locale: 'de'}];
}
 
export default async function LocaleLayout({children, params: {locale}}) {
  let messages;
  try {
    messages = (await import(`../../messages/${locale}.json`)).default;
  } catch (error) {
    notFound();
  }
 
  return (
     <CartProvider>
    <html lang={locale}>
      <body className={montserrat.className}>
        <NextIntlClientProvider locale={locale} messages={messages}>
          <CartMobileIcon />
          <CartMobile />
          {children}
          <CartDesktop />
        </NextIntlClientProvider>
      </body>
    </html>
    </CartProvider>
  );
}